# Generated by Django 4.2 on 2023-04-15 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plural', models.CharField(max_length=52)),
                ('category', models.CharField(max_length=20)),
                ('substitutes', models.CharField(max_length=150)),
                ('vegan', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
