# Generated by Django 4.2 on 2023-04-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_calories_alter_recipe_carbohydrates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='fiber',
            new_name='fibre',
        ),
    ]
