# Generated by Django 4.2 on 2023-04-17 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_recipe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes_received',
            field=models.ManyToManyField(related_name='liked_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
