# Generated by Django 4.2 on 2023-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_name_constituent_ingredient_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
